---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Defines that the role will be deployed on a host machine
is_metal: true

## Verbosity Options
debug: False
verbose: True

## neutron User / Group
trove_system_user_name: trove
trove_system_group_name: trove
trove_system_comment: trove system user
trove_system_shell: /bin/false
trove_system_home_folder: "/var/lib/{{ trove_system_user_name }}"

## DB
trove_galera_user: trove
trove_galera_password: "{{ trove_container_mysql_password }}"
trove_galera_database: trove
trove_db_revision: head
trove_db_config: /etc/trove/trove.conf

## Auth
trove_service_project_name: service
trove_service_project_domain_id: default
trove_service_user_domain_id: default
trove_service_role_name: admin
trove_service_user_name: trove
trove_service_name: trove
trove_service_type: database
trove_service_description: "Trove DB-as-a-service"
trove_service_port: 9696
trove_service_proto: http
trove_service_publicuri: "{{ trove_service_proto }}://{{ external_lb_vip_address }}:{{ trove_service_port }}"
trove_service_publicurl: "{{ trove_service_publicuri }}"
trove_service_adminuri: "{{ trove_service_proto }}://{{ internal_lb_vip_address }}:{{ trove_service_port }}"
trove_service_adminurl: "{{ trove_service_adminuri }}"
trove_service_internaluri: "{{ trove_service_proto }}://{{ internal_lb_vip_address }}:{{ trove_service_port }}"
trove_service_internalurl: "{{ trove_service_internaluri }}"
trove_service_region: RegionOne

## Keystone authentication middleware
trove_keystone_auth_plugin: password

trove_service_task_manager_program_name: trove-taskmanager
trove_service_task_manager_program_config_options: --config-file /etc/trove/trove.conf --config-file /etc/trove/trove-taskmanager.conf
trove_service_task_manager_program_enabled: false

trove_service_conductor_program_name: trove-conductor
trove_service_conductor_program_config_options: --config-file /etc/trove/trove.conf --config-file /etc/trove/trove-conductor.conf
trove_service_conductor_program_enabled: false

trove_service_api_program_name: trove-api
trove_service_api_program_config_options: --config-file /etc/trove/trove.conf
trove_service_api_program_enabled: false

## RPC
trove_rpc_backend: rabbit

## Policy vars
# Provide a list of access controls to update the default policy.json with. These changes will be merged
# with the access controls in the default policy.json. E.g.
#trove_policy_overrides:
#  "create_subnet": "rule:admin_or_network_owner"
#  "get_subnet": "rule:admin_or_owner or rule:shared"

trove_apt_packages:
  - libpq-dev

trove_pip_packages:
  - configobj
  - keystonemiddleware
  - MySQL-python
  - pycrypto
  - python-glanceclient
  - python-keystoneclient
  - python-memcached
  - python-novaclient
  - python-troveclient
  - trove

## Service Names
trove_service_names:
  - trove-api
  - trove-conductor
  - trove-taskmanager
